import { makeStyles } from '@material-ui/core'

export const useStyles = makeStyles((theme) => ({
	[theme.breakpoints.down('sm')]: {
		promoRoot: {
			color: theme.palette.secondary.main,
			paddingBottom: '10px',
		},
		promoWrapper: {
			width: '100%',
			height: '55vh',
			backgroundSize: 'cover',
			backgroundPosition: 'center',
			display: 'inline-flex',
			flexDirection: 'column',
		},
		imageWrapper: {},
		image: { width: '100%' },
		infoWrapper: {
			margin: '30px',
			marginBottom: '5px',
			width: '50%',
			height: '55%',
			textAlign: 'start',
			background: '#dce1ded1',
			boxShadow: '0 0 10px black',
		},
		infoHeader: {
			width: '100%',
			fontFamily: 'IBM Plex Sans, sans-serif',
			letterSpacing: '1px',
			marginLeft: '10px',
			marginBottom: '0px',
		},
		paragraph: {
			letterSpacing: '1px',
			marginLeft: '10px',
			color: theme.palette.text.primary,
			padding: '5px',
			width: '100%',
			background: theme.palette.secondary.main,
		},
		button: {
			background: theme.palette.secondary.main,
			width: '40%',
			marginTop: '30px',
			marginLeft: '30px',
			boxShadow: '0 0 10px black',
		},
	},
	[theme.breakpoints.between('sm', 'md')]: {
		promoRoot: {
			color: theme.palette.secondary.main,
			paddingBottom: '10px',
		},
		promoWrapper: {
			width: '100%',
			height: '30vh',
			backgroundSize: 'cover',
			backgroundPosition: 'center',
			display: 'inline-flex',
			flexDirection: 'column',
		},
		imageWrapper: {},
		image: { width: '100%' },
		infoWrapper: {
			margin: '20px',
			width: '30%',
			textAlign: 'start',
			background: '#dce1ded1',
			boxShadow: '0 0 10px black',
		},
		infoHeader: {
			width: '100%',
			fontFamily: 'IBM Plex Sans, sans-serif',
			letterSpacing: '1px',
			marginLeft: '10px',
			marginBottom: '0px',
		},
		paragraph: {
			letterSpacing: '1px',
			marginLeft: '10px',
			color: theme.palette.text.primary,
			padding: '5px',
			width: '100%',
			background: theme.palette.secondary.main,
		},
		button: {
			background: theme.palette.secondary.main,
			width: '20%',
			marginLeft: '20px',
			boxShadow: '0 0 10px black',
		},
	},
	[theme.breakpoints.between('md', 'lg')]: {
		promoRoot: {
			color: theme.palette.secondary.main,
			paddingBottom: '10px',
		},
		promoWrapper: {
			width: '50%',
			height: '30vh',
			backgroundSize: 'cover',
			backgroundPosition: 'center',
			display: 'inline-flex',
			flexDirection: 'column',
		},
		imageWrapper: {},
		image: { width: '100%' },
		infoWrapper: {
			margin: '20px',
			width: '50%',
			textAlign: 'start',
			background: '#dce1ded1',
			boxShadow: '0 0 10px black',
		},
		infoHeader: {
			width: '100%',
			fontFamily: 'IBM Plex Sans, sans-serif',
			letterSpacing: '1px',
			marginLeft: '10px',
			marginBottom: '0px',
		},
		paragraph: {
			letterSpacing: '1px',
			marginLeft: '10px',
			color: theme.palette.text.primary,
			padding: '5px',
			width: '100%',
			background: theme.palette.secondary.main,
		},
		button: {
			background: theme.palette.secondary.main,
			width: '30%',
			marginLeft: '20px',
			boxShadow: '0 0 10px black',
		},
	},
	[theme.breakpoints.up('xl')]: {
		promoRoot: {
			color: theme.palette.secondary.main,
			background: 'white',
		},
		promoWrapper: {
			width: '50%',
			height: '50vh',
			backgroundSize: 'cover',
			backgroundPosition: 'center',
			display: 'inline-flex',
			flexDirection: 'column',
			justifyContent: 'center',
		},
		imageWrapper: {},
		image: { width: '100%' },
		infoWrapper: {
			marginLeft: '3vw',
			width: '40%',
			height: '20vh',
			textAlign: 'start',
			background: '#dce1ded1',
			boxShadow: '0 0 10px black',
		},
		infoHeader: {
			width: '100%',
			fontSize: '2vw',
			fontFamily: 'IBM Plex Sans, sans-serif',
			letterSpacing: '1px',
			marginLeft: '10px',
			marginBottom: '0px',
		},
		paragraph: {
			letterSpacing: '1px',
			fontSize: '1vw',
			marginLeft: '10px',
			color: theme.palette.text.primary,
			padding: '5px',
			width: '100%',
			height: '20%',
			background: theme.palette.secondary.main,
		},
		button: {
			background: theme.palette.secondary.main,
			width: '30%',
			marginTop: '2vw',
			marginLeft: '3vw',
			boxShadow: '0 0 10px black',
		},
	},
}))
