import { makeStyles } from '@material-ui/core'

export const useStyles = makeStyles((theme) => ({
	[theme.breakpoints.down('sm')]: {
		footerRoot: {
			background: theme.palette.background.paper,
			color: theme.palette.primary.main,
			width: '100%',
			display: 'inline-flex',
			flexDirection: 'column',
			padding: '15px 15px 25px',
		},
		logoWrapper: {
			width: '100%',
			justifyContent: 'center',
			height: '40px',
			marginBottom: '10px',
		},
		logoLink: { width: '50%' },
		footerLogo: { width: '100%' },
		copyrightWrapper: {
			display: 'inline-flex',
			justifyContent: 'center',
			alignItems: 'center',
			flexDirection: 'row',
		},
		copyright: {
			margin: '0',
			padding: '0',
			width: '100%',
			display: 'inline',
			fontSize: '13px',
			textAlign: 'center',
		},
		subCopyright: { marginLeft: '7px', fontSize: '12px' },
		stockPrice: { fontSize: '12px', margin: '0 ' },
		socialWrapper: {
			width: '100%',
			justifyContent: 'center',
			marginBottom: '20px',
			marginTop: '15px',
		},
		iconWrapper: {
			display: 'inline-flex',
			width: '60%',
			justifyContent: 'space-around',
		},
		socialIcon: {},
		arrow: {
			fontSize: '10px',
			margin: '0',
			marginLeft: '4px',
		},
	},
	[theme.breakpoints.between('sm', 'md')]: {
		footerRoot: {
			background: theme.palette.background.paper,
			color: theme.palette.primary.main,
			width: '100%',
			display: 'inline-flex',
			flexDirection: 'row',
			alignItems: 'center',
			padding: '15px 15px 25px',
		},
		logoWrapper: {
			width: '100%',
			justifyContent: 'center',
			alignItems: 'center',
		},
		logoLink: { width: '50%' },
		footerLogo: { width: '100%' },
		copyrightWrapper: {
			display: 'inline-flex',
			justifyContent: 'center',
			alignItems: 'center',
			flexDirection: 'row',
		},
		copyright: {
			margin: '0',
			padding: '0',
			width: '100%',
			display: 'inline',
			fontSize: '13px',
			textAlign: 'center',
		},
		subCopyright: { marginLeft: '7px', fontSize: '12px' },
		stockPrice: { fontSize: '12px', margin: '0 ' },
		socialWrapper: {
			width: '100%',
			justifyContent: 'center',
			marginBottom: '20px',
			marginTop: '15px',
		},
		iconWrapper: {
			display: 'inline-flex',
			width: '60%',
			justifyContent: 'space-around',
		},
		socialIcon: {},
		arrow: {
			fontSize: '10px',
			margin: '0',
			marginLeft: '4px',
		},
	},
	[theme.breakpoints.between('md', 'lg')]: {
		footerRoot: {
			background: theme.palette.background.paper,
			color: theme.palette.primary.main,
			width: '100%',
			display: 'inline-flex',
			flexDirection: 'row',
			alignItems: 'center',
			padding: '15px 15px 25px',
		},
		logoWrapper: {
			width: '100%',
			justifyContent: 'center',
			alignItems: 'center',
		},
		logoLink: { width: '50%' },
		footerLogo: { width: '100%' },
		copyrightWrapper: {
			display: 'inline-flex',
			justifyContent: 'center',
			alignItems: 'center',
			flexDirection: 'row',
		},
		copyright: {
			margin: '0',
			padding: '0',
			width: '100%',
			display: 'inline',
			fontSize: '13px',
			textAlign: 'center',
		},
		subCopyright: { marginLeft: '7px', fontSize: '12px' },
		stockPrice: { fontSize: '12px', margin: '0 ' },
		socialWrapper: {
			width: '100%',
			justifyContent: 'center',
			marginBottom: '20px',
			marginTop: '15px',
		},
		iconWrapper: {
			display: 'inline-flex',
			width: '60%',
			justifyContent: 'space-around',
		},
		socialIcon: {},
		arrow: {
			fontSize: '10px',
			margin: '0',
			marginLeft: '4px',
		},
	},
	[theme.breakpoints.up('xl')]: {
		footerRoot: {
			background: theme.palette.background.paper,
			color: theme.palette.primary.main,
			width: '100%',
			display: 'inline-flex',
			flexDirection: 'row',
			alignItems: 'center',
			padding: '15px 15px 25px',
		},
		logoWrapper: {
			width: '100%',
			justifyContent: 'center',
			alignItems: 'center',
		},
		logoLink: { width: '50%' },
		footerLogo: { width: '100%' },
		copyrightWrapper: {
			display: 'inline-flex',
			justifyContent: 'center',
			alignItems: 'center',
			flexDirection: 'row',
		},
		copyright: {
			margin: '0',
			padding: '0',
			width: '100%',
			display: 'inline',
			fontSize: '13px',
			textAlign: 'center',
		},
		subCopyright: { marginLeft: '7px', fontSize: '12px' },
		stockPrice: { fontSize: '12px', margin: '0 ' },
		socialWrapper: {
			width: '100%',
			justifyContent: 'center',
			marginBottom: '20px',
			marginTop: '15px',
		},
		iconWrapper: {
			display: 'inline-flex',
			width: '60%',
			justifyContent: 'space-around',
		},
		socialIcon: {},
		arrow: {
			fontSize: '10px',
			margin: '0',
			marginLeft: '4px',
		},
	},
}))
